# -*- coding: utf-8 -*-
"""Speech to Text.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z3dJDokKyh7OVwE9GnxCtX17IF-V-DDC
"""

!pip install --upgrade transformers

import transformers
print(transformers.__version__)

import librosa
import torch
import IPython.display as display
from transformers import Wav2Vec2ForCTC, Wav2Vec2Tokenizer
import numpy as np

tokenizer = Wav2Vec2Tokenizer.from_pretrained("facebook/wav2vec2-base-960h")
model = Wav2Vec2ForCTC.from_pretrained("facebook/wav2vec2-base-960h")

audio, sampling_rate = librosa.load("/content/Untitled_0.wav",sr=16000)

audio,sampling_rate

display.Audio("/content/Untitled_0.wav", autoplay=True)

input_values = tokenizer(audio, return_tensors = 'pt').input_values
input_values

logits = model(input_values).logits
logits

predicted_ids = torch.argmax(logits, dim =-1)

transcriptions = tokenizer.decode(predicted_ids[0])

transcriptions

